baseurl = "/"
languageCode = "en-us"
title = "FHI ML"
theme = "hugo-fhi"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Post"
    url = "/post/"

[[menu.main]]
    name = "Dashboards"
    url = "/dashboards/"
    
[[menu.main]]
    name = "R Course"
    url = "/rcourse/"

[[menu.main]]
    name = "Home"
    url = "/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/folkehelseinstituttet/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"


