---
date: "2019-05-05"
layout: center
---

# Registration

[Register for each course here.](https://folkehelse-my.sharepoint.com/:x:/g/personal/richardaubrey_white_fhi_no/EWuoogyngJBPuTQBsbJ--GgBNujH-oFTbYczxBZCma_vLg?e=YpmiMx)

You may register as:

- Oslo student (25 places available)
- Bergen student (15 places available)
- Remote student (5 places available)
- Oslo waitlist (if you aren't in the first 25 to register)

It is free to register and attend the course. If you want to register as a remote student (watching the course via skype for business in real-time) please contact RichardAubrey.White@fhi.no.

If you cannot attend in person, all courses are recorded and will available for your own private viewing.

# Course files and recordings

[All course files and video recordings are available here.](https://folkehelse-my.sharepoint.com/:f:/g/personal/richardaubrey_white_fhi_no/EtKgxNOexhFGp5fOIoymstgBoUUtfeEYwGOOEipncX6tLA?e=ZCdoUh)

Course files and recordings from the Spring 2019 semester are also available.

# Contact points

Oslo/admin/remote students: RichardAubrey.White@fhi.no

Bergen: Nina-Jeanette.Quille@fhi.no

# Student information

SMHB, in collaboration with other departments and område, will be running weekly 1.5 hour R courses in October and November 2019.

The aim of these weekly courses is to keep the participants interested and engaged over a long period of time, which also allows them to improve their R skills on their own during this year long period.
 
The beginning 4 modules are targeted at people with zero R knowledge, and are therefore perfect for people who want to start learning R, or need a refresher.
 
If you have some basic knowledge of R then you can treat each module as an independent course. This means you are welcome to attend some modules (if they interest you) and not attend others (if they don’t interest you).

The planned modules are as follows:

```{r message=FALSE, warning=FALSE, echo=FALSE, results='asis'}
library(magrittr)

data <- list()
data[[1]] <- data.frame(
  date = "02/10/2019",
  time = "1120-1250",
  topic = "Basic R",
  oslo_location = "Rom S24C C 331"
)

data[[2]] <- data.frame(
  date = "09/10/2019",
  time = "1120-1250",
  topic = "Basic R",
  oslo_location = "Rom S24C C 331"
)

data[[3]] <- data.frame(
  date = "23/10/2019",
  time = "1120-1250",
  topic = "Basic R",
  oslo_location = "Rom MT6 701 Utsikten"
)

data[[4]] <- data.frame(
  date = "30/10/2019",
  time = "1120-1250",
  topic = "Basic R",
  oslo_location = "Rom S24C C 331"
)

data[[5]] <- data.frame(
  date = "06/11/2019",
  time = "1120-1250",
  topic = "Advanced R",
  oslo_location = "Rom S24C C 331"
)

data[[6]] <- data.frame(
  date = "13/11/2019",
  time = "1120-1250",
  topic = "Advanced R",
  oslo_location = "Rom S24C C 331"
)

data[[7]] <- data.frame(
  date = "20/11/2019",
  time = "1120-1250",
  topic = "Advanced R",
  oslo_location = "Rom S24C C 331"
)

data <- data.table::rbindlist(data)

tab <- huxtable::hux(
  Date = data$date,
  Time = data$time,
  Topic = data$topic,
  "Oslo location" = data$oslo_location
) %>%
  huxtable::add_colnames() %>%
  huxtable::theme_basic()

cat(huxtable::to_html(tab))
```

To participate in the course you will need to:

- Register
- Bring with you a laptop that has R and RStudio installed on it
- Check that R and RStudio work on your laptop before you show up at the course!
- Be at the course *latest* 1115 so that we can start on time at 1120

# Teacher information

Thank you for volunteering to be a teacher of a course!

To be a teacher you will need to:

- Be available from 1100-1300 on the day of the course (i.e. setup and packdown time)
- Teach from 1120-1250 on the day of the course
- Have skype for business installed (and working) on your laptop
- Have R and RStudio installed and working on your laptop
- Test that you can share your screen (R+RStudio) over skype for business before the day of the course
- Create a course that is (approximately) 45 minutes of lecturing and 45 minutes of practical exercises
- Your course will primarily consist of R-scripts (i.e. `.R` files) with comments inside them
- You will give exercises as homework for the students (roughly 30 minutes of exercises)

# Helper information

Thank you for volunteering to be a helper of a course!

To be a helper you will need to:

- Be available from 1100-1300 on the day of the course (i.e. setup and packdown time)
- Have a good understanding of R


